name: initial launch

on:
  workflow_dispatch:
    inputs:
    # mandatory parameters used by TestOps. More details here: https://docs.qameta.io/allure-testops/integrations/github/#declare-inputs-in-the-github-workflow
      ALLURE_JOB_RUN_ID:
        description: "ALLURE_JOB_RUN_ID service parameter. Leave blank."
        required: false
      ALLURE_USERNAME:
        description: "ALLURE_USERNAME service parameter. Leave blank"
        required: false
    # custom inputs. Should be configured as described here https://docs.qameta.io/allure-testops/integrations/github/#configure-job-to-pass-parameters-to-github-workflow    
      DUMMY_INPUT:
        description: "DUMMY_INPUT should not be added to Job configuration at TestOps since it has a required: false parameter."
        default: 'lmao'
        required: false
      SECOND_DUMMY_INPUT:
        description: "SECOND_DUMMY_INPUT should be added to Job configuration at TestOps since it has a required: true parameter."
        required: true
        type: choice
        options:
        - LOL
        - KEK

run-name: "${{ github.workflow }}-${{ github.run_number }}"

permissions:
  contents: read
  actions: read

jobs:
  prepare-allure-context:
    name: prepare Allure pipeline context
    runs-on: ubuntu-latest
    env:
      ALLURE_ENDPOINT: https://testing.testops.cloud/
      ALLURE_PROJECT_ID: "11844"
      ALLURE_TOKEN: ${{ secrets.ALLURE_TOKEN }}
      ALLURE_RESULTS: allure-results
      ALLURE_LAUNCH_NAME: Python reference launch
      ALLURE_JOB_RUN_ID: ${{ github.event.inputs.ALLURE_JOB_RUN_ID }}
      ALLURE_USERNAME: ${{ github.event.inputs.ALLURE_USERNAME }}

# Build a Valid Reference to the Parent Workflow
# This step is mandatory and is described in detail in the documentation: https://docs.qameta.io/allure-testops/integrations/github/#github-enterprise-suitable-example-script--download
    steps:
      - uses: actions/github-script@v4
        id: allure-job-uid
        with:
          result-encoding: string
          script: |
            const result = await github.actions.getWorkflowRun({
              owner: context.repo.owner,
              repo: context.repo.repo,
              run_id: context.runId,
            });
            return `${context.repo.owner}/${context.repo.repo}/actions/workflows/${result.data.workflow_id}`

      - name: Download and make allurectl executable
        run: |
          wget https://github.com/allure-framework/allurectl/releases/latest/download/allurectl_linux_amd64 -O ./allurectl
          chmod +x ./allurectl

# At this step, we collect all the required pipeline context.
# this is step is needed to pass the full context of the initiating run to the downstream pipeline, so that Allure TestOps can generate the correct link.

      - name: Pack Allure pipeline context
        id: allure-context
        env:
          ALLURE_JOB_UID: ${{ steps.allure-job-uid.outputs.result }}
        run: |
          mkdir -p .allure-context
          ./allurectl ci env --encode > .allure-context/ALLURE_CI_ENV
          ./allurectl ci env --encode | base64 -d

      - name: Upload Allure pipeline context
        uses: actions/upload-artifact@v4
        with:
          name: allure-ci-env
          path: .allure-context/ALLURE_CI_ENV
          retention-days: 1

  execute-functional-test:
    name: execute functional test
    needs: prepare-allure-context
    uses: ./.github/workflows/childWithTestExec.yml
    secrets:
      ALLURE_TOKEN: ${{ secrets.ALLURE_TOKEN }}
